apiVersion: apps/v1
kind: Deployment
metadata:
  name: demobroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demobroker
  template:
    metadata:
      labels:
        app: demobroker
    spec:
      containers:
        - name: demobroker
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://demobroker:9092"  # This is correct now that the service is demobroker
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@demobroker:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"

---
apiVersion: v1
kind: Service
metadata:
  name: demobroker
spec:
  selector:
    app: demobroker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: broker-port  # Name for port 9092
    - protocol: TCP
      port: 9093
      targetPort: 9093
      name: controller-port  # Name for port 9093
  type: ClusterIP

