global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dotnet_producer'
    static_configs:
      - targets: ['producer:7001']  # Ensure this target matches your producer service and port

  - job_name: 'dotnet_consumer'
    static_configs:
      - targets: ['consumer:7002']

