global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dotnet_producer'
    static_configs:
      - targets: ['mybackgroundservice:7001']  
        
  - job_name: 'dotnet_consumer'
    static_configs:
      - targets: [ 'mailconsumer:7002' ]  
        
#  - job_name: 'jmx-exporter'
#    static_configs:
#      - targets: [ 'jmxexporter:7003' ]  
